/*
 * Base de datos de luchadores.
 *
 * Datos reales (aproximados, adulto promedio / macho grande cuando aplica):
 *   peso (kg), largo/altura (m), velocidad máxima (km/h), mordida (PSI).
 *   mordida: null cuando no aplica o no hay medición confiable.
 *
 * Atributos 0-100 (estimaciones para el juego, basadas en su anatomía y comportamiento):
 *   ataque       – letalidad de sus armas naturales (colmillos, garras, cuernos, veneno…)
 *   defensa      – piel, armadura, grasa, huesos: qué tanto aguanta
 *   fuerza       – fuerza RELATIVA a su tamaño (el peso ya se cuenta aparte)
 *   agilidad     – reflejos, maniobrabilidad
 *   ferocidad    – agresividad y disposición a pelear hasta el final
 *   resistencia  – cuánto aguanta una pelea larga
 *   inteligencia – estrategia, capacidad de adaptarse
 *
 * medio: 'tierra' | 'agua' | 'anfibio' | 'aire'
 * nado:  0-1, qué tan bien se defiende un animal terrestre en el agua
 * hogar: arenas donde vive (bonus de local)
 * arenas: ajustes manuales por arena (multiplicador que reemplaza el cálculo)
 *
 * Enjambres: enjambre = true, cantidad = texto ("20.000 abejas").
 *   pesoEfectivo reemplaza al peso en el combate: un enjambre no se noquea de un golpe.
 * especiales: [{ vs: [ids], mult, texto }] – multiplicador de poder contra rivales concretos.
 */
const CATEGORIAS = {
  sabana: { nombre: "Sabana / Tierra", emoji: "🌾" },
  selva: { nombre: "Selva", emoji: "🌴" },
  agua: { nombre: "Agua", emoji: "🌊" },
  nieve: { nombre: "Nieve", emoji: "❄️" },
  aire: { nombre: "Aire", emoji: "🦅" },
  bichos: { nombre: "Bichos", emoji: "🐜" },
  humano: { nombre: "Humanos", emoji: "🧍" },
  paises: { nombre: "Países", emoji: "🌍" },
};

const ARENAS = {
  sabana: { nombre: "Sabana", emoji: "🌾", desc: "Terreno abierto y seco. Sin ventajas para nadie... salvo para los de tierra." },
  selva: { nombre: "Selva", emoji: "🌴", desc: "Vegetación densa, árboles y emboscadas." },
  rio: { nombre: "Río / Pantano", emoji: "🐊", desc: "Agua turbia hasta el cuello. El reino de los anfibios." },
  oceano: { nombre: "Océano", emoji: "🌊", desc: "Mar abierto. Si no sabes nadar, ya perdiste." },
  nieve: { nombre: "Nieve / Hielo", emoji: "❄️", desc: "Frío extremo. Los animales polares juegan de local." },
};

const LUCHADORES = [
  // ───────── SABANA / TIERRA ─────────
  {
    id: "leon", nombre: "León", emoji: "🦁", categoria: "sabana", medio: "tierra", nado: 0.3, hogar: ["sabana"],
    peso: 190, largo: 2.5, velocidad: 80, mordida: 650,
    ataque: 90, defensa: 55, fuerza: 80, agilidad: 85, ferocidad: 85, resistencia: 50, inteligencia: 55,
    armas: "Colmillos de 7 cm y garras retráctiles",
    fortaleza: "Melena que protege el cuello y experiencia peleando contra otros leones.",
    debilidad: "Poca resistencia: se cansa rápido tras un sprint.",
    dato: "Su rugido se oye a 8 km de distancia.",
  },
  {
    id: "elefante", nombre: "Elefante africano", emoji: "🐘", categoria: "sabana", medio: "tierra", nado: 0.6, hogar: ["sabana", "selva"],
    peso: 6000, largo: 6.5, velocidad: 40, mordida: null,
    ataque: 75, defensa: 95, fuerza: 80, agilidad: 25, ferocidad: 60, resistencia: 70, inteligencia: 80,
    armas: "Colmillos de marfil, trompa y 6 toneladas para aplastar",
    fortaleza: "Piel de 2,5 cm de grosor y un tamaño que nadie puede derribar.",
    debilidad: "Lento para girar; las crías son vulnerables (los adultos casi no).",
    dato: "Es el animal terrestre más grande del planeta.",
  },
  {
    id: "rinoceronte", nombre: "Rinoceronte blanco", emoji: "🦏", categoria: "sabana", medio: "tierra", nado: 0.3, hogar: ["sabana"],
    peso: 2300, largo: 4, velocidad: 50, mordida: null,
    ataque: 80, defensa: 95, fuerza: 80, agilidad: 35, ferocidad: 70, resistencia: 60, inteligencia: 35,
    armas: "Cuerno de hasta 1,5 m y embestida de tanque",
    fortaleza: "Piel-armadura de hasta 5 cm de grosor.",
    debilidad: "Muy mala vista: ataca a lo que se mueve.",
    dato: "Su cuerno es de queratina, lo mismo que tus uñas.",
  },
  {
    id: "hipopotamo", nombre: "Hipopótamo", emoji: "🦛", categoria: "sabana", medio: "anfibio", nado: 1, hogar: ["rio", "sabana"],
    peso: 1500, largo: 4, velocidad: 30, mordida: 1800,
    ataque: 85, defensa: 85, fuerza: 75, agilidad: 30, ferocidad: 95, resistencia: 55, inteligencia: 35,
    arenas: { oceano: 0.6 },
    armas: "Colmillos de 50 cm y mandíbula que abre 150°",
    fortaleza: "Territorial y extremadamente agresivo. Mata a más humanos que los leones.",
    debilidad: "Se sobrecalienta fuera del agua.",
    dato: "Suda un líquido rojo que funciona como protector solar.",
  },
  {
    id: "grizzly", nombre: "Oso grizzly", emoji: "🐻", categoria: "sabana", medio: "tierra", nado: 0.6, hogar: ["sabana", "selva", "nieve"], frio: true,
    peso: 300, largo: 2.2, velocidad: 56, mordida: 1160,
    ataque: 90, defensa: 75, fuerza: 90, agilidad: 55, ferocidad: 80, resistencia: 75, inteligencia: 60,
    armas: "Garras de 10 cm y zarpazos que rompen cráneos",
    fortaleza: "Capa de grasa y músculo que absorbe golpes; puede pelear de pie.",
    debilidad: "Menos ágil que los felinos.",
    dato: "Un zarpazo puede romperle la columna a un alce.",
  },
  {
    id: "guepardo", nombre: "Guepardo", emoji: "🐆", categoria: "sabana", medio: "tierra", nado: 0.2, hogar: ["sabana"],
    peso: 50, largo: 1.3, velocidad: 110, mordida: 400,
    ataque: 65, defensa: 25, fuerza: 55, agilidad: 100, ferocidad: 40, resistencia: 25, inteligencia: 50,
    armas: "Velocidad pura y mordida al cuello",
    fortaleza: "El animal terrestre más rápido del mundo.",
    debilidad: "Frágil: evita las peleas porque una herida lo condena.",
    dato: "Pasa de 0 a 100 km/h en unos 3 segundos.",
  },
  {
    id: "hiena", nombre: "Hiena manchada", emoji: "🐺", categoria: "sabana", medio: "tierra", nado: 0.4, hogar: ["sabana"],
    peso: 60, largo: 1.5, velocidad: 60, mordida: 1100,
    ataque: 80, defensa: 50, fuerza: 75, agilidad: 65, ferocidad: 80, resistencia: 90, inteligencia: 70,
    armas: "Mandíbula que tritura huesos",
    fortaleza: "Resistencia infinita: persigue a su presa kilómetros.",
    debilidad: "Sola es mucho menos peligrosa que en manada.",
    dato: "Puede comerse un tercio de su peso en una sola comida.",
  },
  {
    id: "bufalo", nombre: "Búfalo cafre", emoji: "🐃", categoria: "sabana", medio: "tierra", nado: 0.5, hogar: ["sabana"],
    peso: 750, largo: 3, velocidad: 57, mordida: null,
    ataque: 70, defensa: 80, fuerza: 80, agilidad: 45, ferocidad: 90, resistencia: 75, inteligencia: 45,
    armas: "Cuernos fusionados en un 'casco' y embestida",
    fortaleza: "Apodado 'la muerte negra': rencoroso y vengativo.",
    debilidad: "Sus cuernos cubren poco los flancos.",
    dato: "Se sabe que dan la vuelta para emboscar a quien los persigue.",
  },
  {
    id: "canguro", nombre: "Canguro rojo", emoji: "🦘", categoria: "sabana", medio: "tierra", nado: 0.4, hogar: ["sabana"],
    peso: 85, largo: 1.6, velocidad: 70, mordida: null,
    ataque: 55, defensa: 40, fuerza: 80, agilidad: 80, ferocidad: 55, resistencia: 70, inteligencia: 40,
    armas: "Patadas con garras capaces de abrir un vientre",
    fortaleza: "Se apoya en la cola para patear con ambas piernas.",
    debilidad: "Sin colmillos ni garras delanteras de verdad.",
    dato: "Salta hasta 9 metros de un solo brinco.",
  },
  {
    id: "lobo", nombre: "Lobo gris", emoji: "🐺", categoria: "sabana", medio: "tierra", nado: 0.5, hogar: ["sabana", "nieve", "selva"], frio: true,
    peso: 45, largo: 1.6, velocidad: 60, mordida: 400,
    ataque: 75, defensa: 40, fuerza: 60, agilidad: 80, ferocidad: 70, resistencia: 90, inteligencia: 70,
    armas: "Colmillos y trabajo en equipo",
    fortaleza: "Estratega nato y muy resistente.",
    debilidad: "Solo, sin manada, pierde su mayor arma.",
    dato: "Puede recorrer 70 km en una sola noche.",
  },
  {
    id: "komodo", nombre: "Dragón de Komodo", emoji: "🦎", categoria: "sabana", medio: "tierra", nado: 0.6, hogar: ["sabana", "selva"],
    peso: 70, largo: 3, velocidad: 20, mordida: 600,
    ataque: 80, defensa: 70, fuerza: 60, agilidad: 40, ferocidad: 70, resistencia: 50, inteligencia: 35,
    armas: "Dientes aserrados y veneno anticoagulante",
    fortaleza: "Piel con osteodermos (mini-huesos) como cota de malla.",
    debilidad: "Su veneno tarda horas: no gana peleas rápidas.",
    dato: "El lagarto más grande del mundo.",
  },
  {
    id: "tejon", nombre: "Tejón melero", emoji: "🦡", categoria: "sabana", medio: "tierra", nado: 0.3, hogar: ["sabana", "selva"],
    peso: 12, largo: 0.8, velocidad: 30, mordida: null,
    ataque: 60, defensa: 90, fuerza: 80, agilidad: 70, ferocidad: 100, resistencia: 80, inteligencia: 60,
    especiales: [{ vs: ["abejas_africanizadas", "abeja", "enjambre_avispas"], mult: 3, texto: "El tejón melero vive de asaltar colmenas: su piel gruesa ignora las picaduras." }],
    armas: "Garras excavadoras y actitud de 'no me importa nada'",
    fortaleza: "Piel suelta y gruesa: si lo muerden, se gira y contraataca.",
    debilidad: "Es muy pequeño contra depredadores grandes.",
    dato: "Es parcialmente resistente al veneno de cobra.",
  },

  // ───────── SELVA ─────────
  {
    id: "tigre", nombre: "Tigre de Bengala", emoji: "🐅", categoria: "selva", medio: "tierra", nado: 0.8, hogar: ["selva"],
    peso: 220, largo: 2.9, velocidad: 65, mordida: 1050,
    ataque: 95, defensa: 60, fuerza: 85, agilidad: 85, ferocidad: 85, resistencia: 60, inteligencia: 55,
    armas: "Colmillos de 9 cm y garras de 10 cm",
    fortaleza: "Cazador solitario acostumbrado a matar presas más grandes que él.",
    debilidad: "Evita peleas largas: una herida grave lo deja sin cazar.",
    dato: "A diferencia de casi todos los gatos, ama el agua.",
  },
  {
    id: "gorila", nombre: "Gorila espalda plateada", emoji: "🦍", categoria: "selva", medio: "tierra", nado: 0.1, hogar: ["selva"],
    peso: 160, largo: 1.7, velocidad: 40, mordida: 1300,
    ataque: 70, defensa: 60, fuerza: 95, agilidad: 60, ferocidad: 55, resistencia: 60, inteligencia: 75,
    armas: "Brazos descomunales y colmillos de 5 cm",
    fortaleza: "Fuerza bruta estimada en varias veces la de un humano.",
    debilidad: "No es depredador: no está 'diseñado' para matar. No sabe nadar.",
    dato: "Pese a su fama, es vegetariano y pacífico.",
  },
  {
    id: "jaguar", nombre: "Jaguar", emoji: "🐆", categoria: "selva", medio: "tierra", nado: 0.9, hogar: ["selva", "rio"],
    peso: 100, largo: 1.8, velocidad: 80, mordida: 1500,
    ataque: 95, defensa: 55, fuerza: 90, agilidad: 85, ferocidad: 80, resistencia: 55, inteligencia: 55,
    armas: "La mordida más potente de los felinos (atraviesa cráneos)",
    fortaleza: "Caza caimanes dentro del agua.",
    debilidad: "Más pequeño que tigres y leones.",
    dato: "Su nombre viene del tupí 'yaguara': el que mata de un salto.",
  },
  {
    id: "chimpance", nombre: "Chimpancé", emoji: "🐒", categoria: "selva", medio: "tierra", nado: 0.05, hogar: ["selva"],
    peso: 60, largo: 1.2, velocidad: 40, mordida: 1300,
    ataque: 60, defensa: 40, fuerza: 90, agilidad: 80, ferocidad: 75, resistencia: 60, inteligencia: 80,
    armas: "Mordida brutal y fuerza de tracción superior a la humana",
    fortaleza: "Inteligente, usa herramientas y pelea en grupo.",
    debilidad: "No sabe nadar.",
    dato: "Es ~1,35 veces más fuerte que un humano de su mismo peso.",
  },
  {
    id: "anaconda", nombre: "Anaconda verde", emoji: "🐍", categoria: "selva", medio: "anfibio", nado: 1, hogar: ["selva", "rio"],
    peso: 100, largo: 6, velocidad: 8, mordida: null,
    ataque: 75, defensa: 55, fuerza: 95, agilidad: 45, ferocidad: 50, resistencia: 70, inteligencia: 30,
    arenas: { sabana: 0.7, nieve: 0.2, oceano: 0.7 },
    armas: "Constricción: asfixia a su presa",
    fortaleza: "En el agua es casi imposible escapar de ella.",
    debilidad: "Torpe y lenta en tierra firme.",
    dato: "La serpiente más pesada del mundo.",
  },
  {
    id: "cocodrilo", nombre: "Cocodrilo de agua salada", emoji: "🐊", categoria: "selva", medio: "anfibio", nado: 1, hogar: ["rio", "oceano", "selva"],
    peso: 1000, largo: 5.5, velocidad: 29, mordida: 3700,
    ataque: 95, defensa: 90, fuerza: 80, agilidad: 40, ferocidad: 85, resistencia: 50, inteligencia: 40,
    arenas: { oceano: 1.0, sabana: 0.75, nieve: 0.3 },
    armas: "La mordida más fuerte jamás medida + 'giro de la muerte'",
    fortaleza: "Armadura de escamas óseas y emboscada perfecta.",
    debilidad: "En tierra se cansa rápido; su mandíbula abre con poca fuerza.",
    dato: "Su mordida (3.700 PSI) es el récord medido en un animal vivo.",
  },
  {
    id: "arpia", nombre: "Águila arpía", emoji: "🦅", categoria: "aire", medio: "aire", nado: 0, hogar: ["selva"],
    peso: 8, largo: 1, velocidad: 80, mordida: null,
    ataque: 75, defensa: 20, fuerza: 90, agilidad: 90, ferocidad: 70, resistencia: 50, inteligencia: 50,
    armas: "Garras de 13 cm, más grandes que las de un oso",
    fortaleza: "Caza monos y perezosos arrancándolos de los árboles.",
    debilidad: "Frágil si la pelea se vuelve cuerpo a cuerpo en el suelo.",
    dato: "Sus garras aprietan con más de 50 kg de presión.",
  },

  // ───────── AGUA ─────────
  {
    id: "tiburon", nombre: "Tiburón blanco", emoji: "🦈", categoria: "agua", medio: "agua", nado: 1, hogar: ["oceano"],
    peso: 1100, largo: 5, velocidad: 56, mordida: 4000,
    ataque: 95, defensa: 65, fuerza: 80, agilidad: 70, ferocidad: 80, resistencia: 70, inteligencia: 45,
    armas: "300 dientes aserrados en varias filas",
    fortaleza: "Ataque sorpresa desde abajo a toda velocidad.",
    debilidad: "Fuera del agua no dura nada. Las orcas lo cazan.",
    dato: "Huele una gota de sangre en 100 litros de agua.",
  },
  {
    id: "orca", nombre: "Orca", emoji: "🐋", categoria: "agua", medio: "agua", nado: 1, hogar: ["oceano", "nieve"],
    peso: 5500, largo: 8, velocidad: 56, mordida: null,
    ataque: 90, defensa: 80, fuerza: 85, agilidad: 70, ferocidad: 75, resistencia: 90, inteligencia: 95,
    arenas: { nieve: 0.5 },
    armas: "Dientes de 10 cm, embestidas y tácticas de caza",
    fortaleza: "Superdepredador: caza tiburones blancos y ballenas.",
    debilidad: "Necesita agua sí o sí.",
    dato: "Les arranca el hígado a los tiburones blancos con precisión quirúrgica.",
  },
  {
    id: "pulpo", nombre: "Pulpo gigante del Pacífico", emoji: "🐙", categoria: "agua", medio: "agua", nado: 1, hogar: ["oceano"],
    peso: 15, largo: 4, velocidad: 40, mordida: null,
    ataque: 45, defensa: 30, fuerza: 85, agilidad: 85, ferocidad: 30, resistencia: 40, inteligencia: 95,
    armas: "Ocho brazos con 2.000 ventosas y pico venenoso",
    fortaleza: "Camuflaje perfecto y tinta para escapar.",
    debilidad: "Cuerpo blando, sin huesos.",
    dato: "Tiene tres corazones y sangre azul.",
  },
  {
    id: "morena", nombre: "Morena gigante", emoji: "🐍", categoria: "agua", medio: "agua", nado: 1, hogar: ["oceano"],
    peso: 30, largo: 3, velocidad: 20, mordida: null,
    ataque: 70, defensa: 40, fuerza: 60, agilidad: 70, ferocidad: 65, resistencia: 50, inteligencia: 35,
    armas: "Doble mandíbula (como en la película Alien)",
    fortaleza: "Emboscada desde su cueva.",
    debilidad: "No persigue: si te alejas, estás a salvo.",
    dato: "Tiene una segunda mandíbula en la garganta.",
  },
  {
    id: "delfin", nombre: "Delfín mular", emoji: "🐬", categoria: "agua", medio: "agua", nado: 1, hogar: ["oceano"],
    peso: 300, largo: 3, velocidad: 35, mordida: null,
    ataque: 45, defensa: 55, fuerza: 70, agilidad: 90, ferocidad: 45, resistencia: 85, inteligencia: 95,
    armas: "Embestidas con el hocico a toda velocidad",
    fortaleza: "Se sabe que matan tiburones a golpes en grupo.",
    debilidad: "Dientes pensados para peces, no para pelear.",
    dato: "Duermen con medio cerebro a la vez.",
  },

  // ───────── NIEVE ─────────
  {
    id: "oso_polar", nombre: "Oso polar", emoji: "🐻‍❄️", categoria: "nieve", medio: "tierra", nado: 0.9, hogar: ["nieve"], frio: true,
    peso: 450, largo: 2.5, velocidad: 40, mordida: 1200,
    ataque: 90, defensa: 80, fuerza: 90, agilidad: 50, ferocidad: 80, resistencia: 75, inteligencia: 60,
    armas: "Garras de 10 cm y zarpazo de 500+ kg",
    fortaleza: "El carnívoro terrestre más grande del mundo.",
    debilidad: "Se sobrecalienta con facilidad fuera del frío.",
    dato: "Su piel es negra y su pelo es transparente, no blanco.",
  },
  {
    id: "tigre_siberiano", nombre: "Tigre siberiano", emoji: "🐅", categoria: "nieve", medio: "tierra", nado: 0.8, hogar: ["nieve", "selva"], frio: true,
    peso: 280, largo: 3.3, velocidad: 60, mordida: 1050,
    ataque: 95, defensa: 60, fuerza: 85, agilidad: 80, ferocidad: 85, resistencia: 60, inteligencia: 55,
    armas: "Colmillos de 10 cm y garras de 10 cm",
    fortaleza: "El felino más grande del mundo. Caza osos pardos.",
    debilidad: "Igual que todo tigre: le teme a las heridas graves.",
    dato: "Se han documentado tigres siberianos matando osos.",
  },
  {
    id: "morsa", nombre: "Morsa", emoji: "🦭", categoria: "nieve", medio: "anfibio", nado: 1, hogar: ["nieve", "oceano"], frio: true,
    peso: 1200, largo: 3.5, velocidad: 35, mordida: null,
    ataque: 70, defensa: 85, fuerza: 70, agilidad: 30, ferocidad: 65, resistencia: 65, inteligencia: 50,
    arenas: { sabana: 0.5, selva: 0.4 },
    armas: "Colmillos de hasta 1 metro",
    fortaleza: "Piel de 4 cm y 10 cm de grasa: los osos polares lo piensan dos veces.",
    debilidad: "Muy torpe fuera del agua.",
    dato: "Usa sus colmillos como piolet para salir del agua.",
  },
  {
    id: "gloton", nombre: "Glotón", emoji: "🦡", categoria: "nieve", medio: "tierra", nado: 0.4, hogar: ["nieve"], frio: true,
    peso: 18, largo: 1, velocidad: 48, mordida: null,
    ataque: 65, defensa: 70, fuerza: 85, agilidad: 70, ferocidad: 100, resistencia: 85, inteligencia: 60,
    armas: "Garras y mordida capaz de romper huesos congelados",
    fortaleza: "Le roba presas a lobos y osos. Sin miedo alguno.",
    debilidad: "Pequeño: la ferocidad no compensa 20 veces menos peso.",
    dato: "Se le conoce como 'el demonio del norte'.",
  },
  {
    id: "leopardo_nieves", nombre: "Leopardo de las nieves", emoji: "🐆", categoria: "nieve", medio: "tierra", nado: 0.3, hogar: ["nieve"], frio: true,
    peso: 45, largo: 1.3, velocidad: 65, mordida: 500,
    ataque: 75, defensa: 45, fuerza: 80, agilidad: 95, ferocidad: 55, resistencia: 60, inteligencia: 55,
    armas: "Colmillos y saltos de 15 metros",
    fortaleza: "Maestro de las montañas: caza cabras en acantilados.",
    debilidad: "Tímido, evita confrontaciones.",
    dato: "Usa su cola como bufanda para dormir.",
  },

  // ───────── AIRE ─────────
  {
    id: "aguila_real", nombre: "Águila real", emoji: "🦅", categoria: "aire", medio: "aire", nado: 0, hogar: ["sabana", "nieve"],
    peso: 5, largo: 0.9, velocidad: 240, mordida: null,
    ataque: 70, defensa: 15, fuerza: 85, agilidad: 95, ferocidad: 70, resistencia: 50, inteligencia: 50,
    armas: "Garras y picada a 240 km/h",
    fortaleza: "Ha cazado ciervos jóvenes y hasta lobos (con ayuda humana en Asia).",
    debilidad: "Si la atrapan en el suelo, pierde casi toda ventaja.",
    dato: "Su vista es 4-8 veces más aguda que la humana.",
  },

  // ───────── HUMANOS ─────────
  {
    id: "humano", nombre: "Humano promedio", emoji: "🧍", categoria: "humano", medio: "tierra", nado: 0.4, hogar: [],
    peso: 75, largo: 1.72, velocidad: 24, mordida: 160,
    ataque: 15, defensa: 20, fuerza: 40, agilidad: 45, ferocidad: 40, resistencia: 85, inteligencia: 100,
    armas: "Puños... y mucha confianza",
    fortaleza: "La mayor resistencia del reino animal (corre durante horas) y el cerebro más grande.",
    debilidad: "Sin garras, sin colmillos, piel delgada.",
    dato: "Somos de los pocos animales que regulan temperatura sudando por todo el cuerpo.",
  },
  {
    id: "mma", nombre: "Peleador de MMA", emoji: "🥋", categoria: "humano", medio: "tierra", nado: 0.5, hogar: [],
    peso: 84, largo: 1.83, velocidad: 32, mordida: 160,
    ataque: 30, defensa: 30, fuerza: 55, agilidad: 65, ferocidad: 70, resistencia: 90, inteligencia: 100,
    armas: "Golpes, patadas, llaves y estrangulaciones",
    fortaleza: "Técnica entrenada y experiencia real de combate.",
    debilidad: "Las llaves no funcionan igual en un animal de 4 patas.",
    dato: "Un golpe profesional puede superar los 500 kg de fuerza.",
  },
  {
    id: "strongman", nombre: "Strongman", emoji: "🏋️", categoria: "humano", medio: "tierra", nado: 0.3, hogar: [],
    peso: 180, largo: 1.95, velocidad: 20, mordida: 160,
    ataque: 20, defensa: 40, fuerza: 50, agilidad: 30, ferocidad: 50, resistencia: 60, inteligencia: 100,
    armas: "Agarres y levantamientos de medio tonelada",
    fortaleza: "El humano más fuerte posible: levanta más de 500 kg.",
    debilidad: "Lento y sin armas naturales.",
    dato: "El récord de peso muerto supera los 500 kg.",
  },
  {
    id: "cazador", nombre: "Cazador con lanza", emoji: "🗡️", categoria: "humano", medio: "tierra", nado: 0.4, hogar: [],
    peso: 70, largo: 1.75, velocidad: 28, mordida: 160,
    ataque: 70, defensa: 25, fuerza: 45, agilidad: 55, ferocidad: 60, resistencia: 95, inteligencia: 100,
    armas: "Lanza de 2 m con punta de acero",
    fortaleza: "La herramienta que nos hizo cazar mamuts. Mantiene la distancia.",
    debilidad: "Si falla el primer golpe, está en problemas.",
    dato: "Los masái tradicionalmente cazaban leones con lanza.",
  },

  // ───────── BICHOS ─────────
  {
    id: "hormiga_bala", nombre: "Hormiga bala", emoji: "🐜", categoria: "bichos", medio: "tierra", nado: 0.1, hogar: ["selva"],
    peso: 0.00004, largo: 0.03, velocidad: 0.2, mordida: null,
    ataque: 85, defensa: 30, fuerza: 100, agilidad: 40, ferocidad: 80, resistencia: 50, inteligencia: 10,
    arenas: { nieve: 0.3 },
    armas: "La picadura más dolorosa del mundo (nivel 4+ en la escala de Schmidt)",
    fortaleza: "Su picadura se siente 'como un disparo' y el dolor dura 24 horas.",
    debilidad: "Pesa 0,04 gramos. Un pisotón y se acabó.",
    dato: "Los sateré-mawé usan guantes llenos de hormigas bala como rito de iniciación.",
  },
  {
    id: "hormigas_legionarias", nombre: "Colonia de hormigas legionarias", emoji: "🐜", categoria: "bichos", medio: "tierra", nado: 0.2, hogar: ["selva", "sabana"],
    enjambre: true, cantidad: "20 millones de hormigas",
    peso: 30, pesoEfectivo: 20, largo: 100, velocidad: 0.02, mordida: null,
    ataque: 40, defensa: 100, fuerza: 100, agilidad: 5, ferocidad: 100, resistencia: 100, inteligencia: 40,
    arenas: { nieve: 0.15, oceano: 0.1 },
    armas: "20 millones de mandíbulas que desarman lo que encuentran",
    fortaleza: "No se le puede ganar a golpes: por cada una que aplastas, llegan mil.",
    debilidad: "Avanza a 20 metros por hora. Basta con… caminar.",
    dato: "Una colonia puede cazar 500.000 presas en un solo día.",
  },
  {
    id: "tarantula", nombre: "Tarántula Goliat", emoji: "🕷️", categoria: "bichos", medio: "tierra", nado: 0.1, hogar: ["selva"],
    peso: 0.175, largo: 0.3, velocidad: 2, mordida: null,
    ataque: 60, defensa: 35, fuerza: 70, agilidad: 50, ferocidad: 60, resistencia: 40, inteligencia: 15,
    arenas: { nieve: 0.3 },
    armas: "Colmillos de 2,5 cm y pelos urticantes que lanza a la cara",
    fortaleza: "La araña más grande del mundo: del tamaño de un plato.",
    debilidad: "Su veneno a un humano le duele como una avispa, nada más.",
    dato: "Pese a su nombre en inglés ('come-pájaros'), casi nunca come pájaros.",
  },
  {
    id: "viuda_negra", nombre: "Viuda negra", emoji: "🕷️", categoria: "bichos", medio: "tierra", nado: 0.05, hogar: ["sabana"],
    peso: 0.001, largo: 0.04, velocidad: 1, mordida: null,
    ataque: 90, defensa: 10, fuerza: 60, agilidad: 50, ferocidad: 50, resistencia: 40, inteligencia: 15,
    arenas: { nieve: 0.3 },
    armas: "Neurotoxina 15 veces más potente que el veneno de cascabel",
    fortaleza: "Una gota de su veneno tiene un poder absurdo para su tamaño.",
    debilidad: "Inyecta tan poco que rara vez mata a un adulto.",
    dato: "La hembra a veces se come al macho después del apareamiento.",
  },
  {
    id: "escorpion", nombre: "Escorpión amarillo", emoji: "🦂", categoria: "bichos", medio: "tierra", nado: 0.05, hogar: ["sabana"],
    peso: 0.002, largo: 0.1, velocidad: 1.5, mordida: null,
    ataque: 90, defensa: 55, fuerza: 70, agilidad: 55, ferocidad: 70, resistencia: 60, inteligencia: 15,
    arenas: { nieve: 0.3 },
    armas: "Aguijón con uno de los venenos más peligrosos entre escorpiones",
    fortaleza: "Exoesqueleto duro y sobrevive un año sin comer.",
    debilidad: "Es chiquito y se lo come cualquier suricata.",
    dato: "Brilla en color azul bajo luz ultravioleta.",
  },
  {
    id: "avispa_gigante", nombre: "Avispa gigante asiática", emoji: "🐝", categoria: "bichos", medio: "aire", nado: 0, hogar: ["selva"],
    peso: 0.004, largo: 0.05, velocidad: 40, mordida: null,
    ataque: 90, defensa: 45, fuerza: 90, agilidad: 85, ferocidad: 95, resistencia: 60, inteligencia: 20,
    arenas: { nieve: 0.2 },
    armas: "Aguijón de 6 mm que atraviesa trajes de apicultor",
    fortaleza: "Una sola puede matar 40 abejas por minuto.",
    debilidad: "Contra algo más grande que un ratón, es una picadura muy (muy) dolorosa y ya.",
    dato: "Apodada 'avispa asesina'. Sus mandíbulas decapitan abejas.",
  },
  {
    id: "enjambre_avispas", nombre: "Nido de avispas gigantes", emoji: "🐝", categoria: "bichos", medio: "aire", nado: 0, hogar: ["selva"],
    enjambre: true, cantidad: "500 avispas gigantes",
    peso: 2, pesoEfectivo: 40, largo: 5, velocidad: 40, mordida: null,
    ataque: 90, defensa: 90, fuerza: 60, agilidad: 100, ferocidad: 100, resistencia: 60, inteligencia: 30,
    arenas: { nieve: 0.15, oceano: 0.4, rio: 0.5 },
    armas: "500 aguijones con veneno que destruye tejidos",
    fortaleza: "Persiguen durante cientos de metros. No hay a dónde correr.",
    debilidad: "Si te metes al agua, no pueden seguirte.",
    dato: "En Japón causan más muertes al año que osos y serpientes juntos.",
  },
  {
    id: "abeja", nombre: "Abeja", emoji: "🐝", categoria: "bichos", medio: "aire", nado: 0, hogar: ["sabana", "selva"],
    peso: 0.0001, largo: 0.015, velocidad: 25, mordida: null,
    ataque: 50, defensa: 15, fuerza: 70, agilidad: 80, ferocidad: 60, resistencia: 40, inteligencia: 20,
    arenas: { nieve: 0.2 },
    armas: "Un aguijón… de un solo uso",
    fortaleza: "Da la vida por su colmena. Literalmente.",
    debilidad: "Si pica, muere.",
    dato: "Para hacer 1 kg de miel, las abejas vuelan el equivalente a 4 vueltas al mundo.",
  },
  {
    id: "abejas_africanizadas", nombre: "Enjambre de abejas africanizadas", emoji: "🐝", categoria: "bichos", medio: "aire", nado: 0, hogar: ["sabana", "selva"],
    enjambre: true, cantidad: "20.000 abejas asesinas",
    peso: 2, pesoEfectivo: 60, largo: 5, velocidad: 25, mordida: null,
    ataque: 70, defensa: 90, fuerza: 20, agilidad: 100, ferocidad: 100, resistencia: 70, inteligencia: 30,
    arenas: { nieve: 0.15, oceano: 0.4, rio: 0.5 },
    especiales: [
      { vs: ["elefante"], mult: 4, texto: "Los elefantes les tienen pánico a las abejas (es real: en África usan colmenas como cercas anti-elefantes)." },
      { vs: ["avispa_gigante"], mult: 3, texto: "Las abejas rodean a la avispa y la cocinan viva subiendo la temperatura a 46 °C." },
    ],
    armas: "Miles de aguijones y persecución de hasta 400 metros",
    fortaleza: "Atacan 10 veces más abejas que en un enjambre normal.",
    debilidad: "Si te metes al agua, esperan en la superficie… pero pueden esperar un buen rato.",
    dato: "Nacieron de un experimento en Brasil en 1957 y se expandieron por toda América.",
  },
  {
    id: "pirañas", nombre: "Cardumen de pirañas", emoji: "🐟", categoria: "bichos", medio: "agua", nado: 1, hogar: ["rio"],
    enjambre: true, cantidad: "100 pirañas",
    peso: 70, pesoEfectivo: 70, largo: 0.3, velocidad: 25, mordida: 72,
    ataque: 80, defensa: 70, fuerza: 60, agilidad: 85, ferocidad: 70, resistencia: 60, inteligencia: 20,
    arenas: { rio: 1.25, oceano: 0.3 },
    armas: "Dientes triangulares afilados como navajas",
    fortaleza: "Para su tamaño, tienen una de las mordidas más potentes que existen.",
    debilidad: "Solo viven en agua dulce: en el mar no duran nada.",
    dato: "Su fama viene en parte de Theodore Roosevelt, que vio un 'show' preparado con pirañas hambrientas.",
  },

  // ───────── MÁS HUMANOS ─────────
  {
    id: "boxeador", nombre: "Boxeador profesional", emoji: "🥊", categoria: "humano", medio: "tierra", nado: 0.4, hogar: [],
    peso: 80, largo: 1.8, velocidad: 32, mordida: 160,
    ataque: 35, defensa: 35, fuerza: 55, agilidad: 70, ferocidad: 70, resistencia: 90, inteligencia: 100,
    armas: "Jab, gancho y uppercut",
    fortaleza: "Esquiva, aguanta golpes y pega durísimo.",
    debilidad: "Solo sabe usar las manos. Y los animales no respetan el reglamento.",
    dato: "Un golpe de un peso pesado puede llegar a unos 1.000 kg de fuerza.",
  },
  {
    id: "muaythai", nombre: "Peleador de Muay Thai", emoji: "🦵", categoria: "humano", medio: "tierra", nado: 0.4, hogar: [],
    peso: 70, largo: 1.75, velocidad: 32, mordida: 160,
    ataque: 40, defensa: 40, fuerza: 55, agilidad: 70, ferocidad: 75, resistencia: 90, inteligencia: 100,
    armas: "Los 8 miembros: puños, codos, rodillas y tibias de acero",
    fortaleza: "Espinillas endurecidas a base de patear troncos de plátano.",
    debilidad: "Patearle la pierna a un rinoceronte no tiene el mismo efecto.",
    dato: "Le dicen 'el arte de las ocho extremidades'.",
  },
  {
    id: "crossfitero", nombre: "Crossfitero", emoji: "🏃", categoria: "humano", medio: "tierra", nado: 0.5, hogar: [],
    peso: 85, largo: 1.78, velocidad: 28, mordida: 160,
    ataque: 15, defensa: 30, fuerza: 60, agilidad: 55, ferocidad: 50, resistencia: 95, inteligencia: 95,
    armas: "Burpees infinitos y contarle a todos que hace CrossFit",
    fortaleza: "Cardio, fuerza y cero miedo a sufrir.",
    debilidad: "Se detiene a grabar su pelea para Instagram.",
    dato: "Antes de empezar la pelea, ya te contó que hace CrossFit.",
  },
  {
    id: "fisicoculturista", nombre: "Fisicoculturista", emoji: "💪", categoria: "humano", medio: "tierra", nado: 0.3, hogar: [],
    peso: 110, largo: 1.8, velocidad: 22, mordida: 160,
    ataque: 20, defensa: 40, fuerza: 55, agilidad: 25, ferocidad: 45, resistencia: 40, inteligencia: 100,
    armas: "Posar tan fuerte que el rival se intimide",
    fortaleza: "110 kg de músculo puro.",
    debilidad: "Músculo de exhibición: poco cardio. Y no pelea si le toca día de pierna.",
    dato: "Antes de una competencia deshidratan su cuerpo para marcar más los músculos.",
  },
  {
    id: "sumo", nombre: "Luchador de sumo", emoji: "🍙", categoria: "humano", medio: "tierra", nado: 0.4, hogar: [],
    peso: 150, largo: 1.83, velocidad: 25, mordida: 160,
    ataque: 25, defensa: 60, fuerza: 60, agilidad: 40, ferocidad: 70, resistencia: 50, inteligencia: 100,
    armas: "Embestida de 150 kg y empujones que te sacan del ring",
    fortaleza: "Centro de gravedad bajísimo: casi imposible de derribar.",
    debilidad: "Los animales no saben que tienen que salir del círculo para perder.",
    dato: "Los luchadores de sumo comen chanko-nabe: hasta 10.000 calorías al día.",
  },
  {
    id: "latino", nombre: "Latino promedio", emoji: "🩴", categoria: "paises", medio: "tierra", nado: 0.4, hogar: [],
    peso: 75, largo: 1.7, velocidad: 24, mordida: 160,
    ataque: 20, defensa: 30, fuerza: 42, agilidad: 50, ferocidad: 55, resistencia: 85, inteligencia: 100,
    armas: "La chancla voladora heredada de mamá (precisión teledirigida)",
    fortaleza: "Sobrevivió a los chanclazos de su mamá: tolerancia al dolor legendaria.",
    debilidad: "Se distrae si alguien pone salsa o reguetón.",
    dato: "Puede pelear, bailar y cocinar para 20 personas al mismo tiempo.",
  },
  {
    id: "chino", nombre: "Chino promedio", emoji: "🥢", categoria: "paises", medio: "tierra", nado: 0.4, hogar: [],
    peso: 70, largo: 1.72, velocidad: 24, mordida: 160,
    ataque: 20, defensa: 25, fuerza: 42, agilidad: 55, ferocidad: 45, resistencia: 85, inteligencia: 100,
    armas: "Kung fu aprendido en películas de Jackie Chan (y unos palillos)",
    fortaleza: "Somos 1.400 millones: siempre hay un primo que sí sabe kung fu.",
    debilidad: "El abuelo del parque que hace Tai Chi pelea mejor que él.",
    dato: "China es una potencia mundial en halterofilia olímpica.",
  },
  {
    id: "japones", nombre: "Japonés promedio", emoji: "🎌", categoria: "paises", medio: "tierra", nado: 0.5, hogar: [],
    peso: 70, largo: 1.71, velocidad: 24, mordida: 160,
    ataque: 20, defensa: 25, fuerza: 42, agilidad: 55, ferocidad: 40, resistencia: 85, inteligencia: 100,
    armas: "Una reverencia educada… seguida de una llave de judo",
    fortaleza: "El judo, el karate y el aikido nacieron en Japón.",
    debilidad: "Pide disculpas antes de golpear, y ahí pierde el factor sorpresa.",
    dato: "Japón tiene una de las esperanzas de vida más altas del mundo: te gana por desgaste.",
  },
  {
    id: "coreano", nombre: "Coreano promedio", emoji: "🫰", categoria: "paises", medio: "tierra", nado: 0.4, hogar: [],
    peso: 74, largo: 1.75, velocidad: 25, mordida: 160,
    ataque: 25, defensa: 30, fuerza: 45, agilidad: 55, ferocidad: 50, resistencia: 85, inteligencia: 100,
    armas: "Patada de taekwondo (arte marcial nacional)",
    fortaleza: "Los hombres hacen un servicio militar obligatorio de ~18 meses.",
    debilidad: "Si se le acaba el kimchi, pierde la mitad de su poder.",
    dato: "El taekwondo es deporte olímpico desde Sídney 2000.",
  },
  {
    id: "kpoper", nombre: "Fan del K-pop", emoji: "💜", categoria: "humano", medio: "tierra", nado: 0.4, hogar: [],
    peso: 58, largo: 1.65, velocidad: 22, mordida: 160,
    ataque: 15, defensa: 20, fuerza: 35, agilidad: 55, ferocidad: 100, resistencia: 95, inteligencia: 95,
    armas: "Lightstick oficial y un fandom de millones listo para funarte",
    fortaleza: "Aguanta 12 horas de fila para un concierto: resistencia sobrehumana. Ferocidad máxima si insultas a su bias.",
    debilidad: "Se paraliza si empieza a sonar una canción de su grupo favorito.",
    dato: "Los fandoms de K-pop han llegado a colapsar páginas de venta de entradas.",
  },

  // ───────── PAÍSES (estereotipos en buena onda) ─────────
  {
    id: "estadounidense", nombre: "Estadounidense promedio", emoji: "🍔", categoria: "paises", medio: "tierra", nado: 0.4, hogar: [],
    peso: 90, largo: 1.75, velocidad: 24, mordida: 160,
    ataque: 20, defensa: 30, fuerza: 45, agilidad: 45, ferocidad: 60, resistencia: 70, inteligencia: 100,
    armas: "Un grito de ¡FREEDOM! y una demanda judicial",
    fortaleza: "Se cree protagonista de película de acción: nunca acepta que perdió.",
    debilidad: "Si se lastima, le sale más caro el hospital que perder la pelea.",
    dato: "Estados Unidos tiene más medallas olímpicas que cualquier otro país.",
  },
  {
    id: "canadiense", nombre: "Canadiense promedio", emoji: "🍁", categoria: "paises", medio: "tierra", nado: 0.4, hogar: [],
    frio: true, arenas: { nieve: 1.1 },
    peso: 84, largo: 1.78, velocidad: 25, mordida: 160,
    ataque: 25, defensa: 35, fuerza: 48, agilidad: 55, ferocidad: 50, resistencia: 85, inteligencia: 100,
    armas: "Pelea de hockey sobre hielo… con disculpas incluidas",
    fortaleza: "En el hockey las peleas son parte del juego: sabe pelear sobre hielo.",
    debilidad: "Pide perdón cada vez que conecta un golpe.",
    dato: "Canadá tiene más lagos que el resto del mundo junto.",
  },
  {
    id: "luchador_mexicano", nombre: "Luchador mexicano", emoji: "🤼", categoria: "paises", medio: "tierra", nado: 0.4, hogar: [],
    peso: 90, largo: 1.75, velocidad: 30, mordida: 160,
    ataque: 35, defensa: 40, fuerza: 55, agilidad: 75, ferocidad: 75, resistencia: 85, inteligencia: 100,
    armas: "Tope suicida desde la tercera cuerda y la máscara sagrada",
    fortaleza: "Vuela por los aires como si no existiera la gravedad.",
    debilidad: "Si le quitan la máscara, pierde su honor (y la pelea).",
    dato: "La lucha libre es Patrimonio Cultural de la Ciudad de México desde 2018.",
  },
  {
    id: "brasileno", nombre: "Brasileño promedio", emoji: "⚽", categoria: "paises", medio: "tierra", nado: 0.4, hogar: [],
    peso: 75, largo: 1.73, velocidad: 26, mordida: 160,
    ataque: 30, defensa: 30, fuerza: 45, agilidad: 70, ferocidad: 55, resistencia: 85, inteligencia: 100,
    armas: "Jiu-jitsu brasileño y una chilena de fútbol a la cara",
    fortaleza: "El jiu-jitsu brasileño es de las artes marciales más efectivas en el suelo.",
    debilidad: "Si suena samba, deja todo y se pone a bailar.",
    dato: "Brasil ganó 5 Mundiales de fútbol, más que ningún país.",
  },
  {
    id: "argentino", nombre: "Argentino promedio", emoji: "🧉", categoria: "paises", medio: "tierra", nado: 0.4, hogar: [],
    peso: 76, largo: 1.74, velocidad: 24, mordida: 160,
    ataque: 22, defensa: 28, fuerza: 43, agilidad: 55, ferocidad: 70, resistencia: 80, inteligencia: 100,
    armas: "Mate hirviendo y un sermón de por qué Messi es el mejor de la historia",
    fortaleza: "Autoestima nivel dios: nunca cree que va a perder.",
    debilidad: "Discute con el árbitro más de lo que pelea.",
    dato: "Argentina tiene 3 Copas del Mundo (1978, 1986 y 2022).",
  },
  {
    id: "britanico", nombre: "Británico promedio", emoji: "🫖", categoria: "paises", medio: "tierra", nado: 0.4, hogar: [],
    peso: 84, largo: 1.76, velocidad: 24, mordida: 160,
    ataque: 20, defensa: 28, fuerza: 42, agilidad: 45, ferocidad: 45, resistencia: 80, inteligencia: 100,
    armas: "Té hirviendo y un 'sorry' pasivo-agresivo",
    fortaleza: "Hace fila con disciplina militar: paciencia infinita.",
    debilidad: "A las 5 en punto se detiene para tomar el té.",
    dato: "En el Reino Unido se toman unas 100 millones de tazas de té al día.",
  },
  {
    id: "frances", nombre: "Francés promedio", emoji: "🥖", categoria: "paises", medio: "tierra", nado: 0.4, hogar: [],
    peso: 77, largo: 1.76, velocidad: 24, mordida: 160,
    ataque: 25, defensa: 25, fuerza: 42, agilidad: 60, ferocidad: 40, resistencia: 75, inteligencia: 100,
    armas: "Baguette del día anterior (dura como un bate) y técnica de esgrima",
    fortaleza: "Francia es una potencia olímpica en esgrima.",
    debilidad: "Puede declararse en huelga a mitad de la pelea.",
    dato: "En Francia se hornean miles de millones de baguettes al año.",
  },
  {
    id: "aleman", nombre: "Alemán promedio", emoji: "🥨", categoria: "paises", medio: "tierra", nado: 0.4, hogar: [],
    peso: 85, largo: 1.8, velocidad: 24, mordida: 160,
    ataque: 22, defensa: 32, fuerza: 48, agilidad: 45, ferocidad: 45, resistencia: 85, inteligencia: 100,
    armas: "Jarra de cerveza de 1 litro y eficiencia alemana",
    fortaleza: "Llega puntual y pelea con precisión de ingeniería.",
    debilidad: "Si el rival no respeta el reglamento, se ofende muchísimo.",
    dato: "En el Oktoberfest se sirven millones de litros de cerveza cada año.",
  },
  {
    id: "italiano", nombre: "Italiano promedio", emoji: "🤌", categoria: "paises", medio: "tierra", nado: 0.4, hogar: [],
    peso: 78, largo: 1.75, velocidad: 24, mordida: 160,
    ataque: 20, defensa: 25, fuerza: 42, agilidad: 55, ferocidad: 60, resistencia: 75, inteligencia: 100,
    armas: "Gestos con las manos que hipnotizan y un sartén de pasta",
    fortaleza: "Drama nivel ópera: convence al árbitro de que él es la víctima.",
    debilidad: "Se desconcentra si alguien le pone piña a la pizza.",
    dato: "En Italia existen más de 300 tipos de pasta.",
  },
  {
    id: "espanol", nombre: "Español promedio", emoji: "🥘", categoria: "paises", medio: "tierra", nado: 0.4, hogar: [],
    peso: 76, largo: 1.74, velocidad: 24, mordida: 160,
    ataque: 20, defensa: 25, fuerza: 42, agilidad: 65, ferocidad: 55, resistencia: 75, inteligencia: 100,
    armas: "Capote de torero y un '¡venga, hombre!'",
    fortaleza: "Tradición de esquivar embestidas: difícil de atrapar.",
    debilidad: "A las 3 de la tarde se echa la siesta, pase lo que pase.",
    dato: "En España se suele cenar a las 10 de la noche.",
  },
  {
    id: "ruso", nombre: "Ruso promedio", emoji: "🪆", categoria: "paises", medio: "tierra", nado: 0.4,
    frio: true, hogar: ["nieve"],
    especiales: [{ vs: ["grizzly", "oso_polar"], mult: 1.3, texto: "Internet está lleno de videos de rusos conviviendo con osos. Algo sabe." }],
    peso: 80, largo: 1.76, velocidad: 24, mordida: 160,
    ataque: 22, defensa: 35, fuerza: 50, agilidad: 45, ferocidad: 60, resistencia: 90, inteligencia: 100,
    armas: "Resistencia al frío y una mirada que no parpadea",
    fortaleza: "Creció con inviernos de -40 °C: juega de local en la nieve.",
    debilidad: "Sin su gorro ushanka pierde el 20% de su poder.",
    dato: "Rusia es el país más grande del mundo.",
  },
  {
    id: "keniano", nombre: "Maratonista keniano", emoji: "🏅", categoria: "paises", medio: "tierra", nado: 0.4, hogar: [],
    peso: 58, largo: 1.7, velocidad: 36, mordida: 160,
    ataque: 15, defensa: 20, fuerza: 40, agilidad: 75, ferocidad: 40, resistencia: 100, inteligencia: 100,
    armas: "Correr. Correr hasta que el rival se desmaye de cansancio.",
    fortaleza: "Kenia domina las maratones del mundo: resistencia infinita.",
    debilidad: "Pega como cualquier humano: su plan es ganar por agotamiento.",
    dato: "Eliud Kipchoge corrió una maratón en menos de 2 horas (1:59:40).",
  },
  {
    id: "sudafricano", nombre: "Guía de safari sudafricano", emoji: "🧭", categoria: "paises", medio: "tierra", nado: 0.4,
    hogar: ["sabana"],
    peso: 80, largo: 1.78, velocidad: 26, mordida: 160,
    ataque: 22, defensa: 30, fuerza: 45, agilidad: 55, ferocidad: 50, resistencia: 85, inteligencia: 100,
    armas: "Conocimiento total de la sabana y un sombrero de explorador",
    fortaleza: "Sabe exactamente qué hacer cuando un león lo mira fijamente.",
    debilidad: "Su primer consejo siempre es 'no corras'… y luego corre.",
    dato: "Sudáfrica ha ganado 4 Mundiales de rugby.",
  },
  {
    id: "indio", nombre: "Indio promedio", emoji: "🧘", categoria: "paises", medio: "tierra", nado: 0.4, hogar: [],
    peso: 66, largo: 1.66, velocidad: 24, mordida: 160,
    ataque: 18, defensa: 25, fuerza: 40, agilidad: 70, ferocidad: 40, resistencia: 85, inteligencia: 100,
    armas: "Flexibilidad de yoga y un bate de cricket",
    fortaleza: "Maestro de yoga: se dobla en posiciones imposibles para esquivar.",
    debilidad: "Si hay un partido de cricket en la tele, la pelea puede esperar.",
    dato: "El yoga nació en la India hace miles de años.",
  },
  {
    id: "australiano", nombre: "Australiano promedio", emoji: "🏄", categoria: "paises", medio: "tierra", nado: 0.4, hogar: [],
    especiales: [{ vs: ["tarantula", "viuda_negra", "escorpion", "canguro", "cocodrilo"], mult: 1.6, texto: "Un australiano pelea contra arañas, canguros y cocodrilos antes del desayuno." }],
    peso: 86, largo: 1.79, velocidad: 25, mordida: 160,
    ataque: 22, defensa: 35, fuerza: 48, agilidad: 55, ferocidad: 65, resistencia: 85, inteligencia: 100,
    armas: "Boomerang y cero miedo a absolutamente nada",
    fortaleza: "Vive en un país donde todo quiere matarlo: ya está curtido.",
    debilidad: "Se confía demasiado: 'She'll be right, mate'.",
    dato: "Australia tiene algunas de las serpientes más venenosas del mundo.",
  },
  {
    id: "neozelandes", nombre: "Neozelandés (All Black)", emoji: "🥝", categoria: "paises", medio: "tierra", nado: 0.4, hogar: [],
    peso: 102, largo: 1.87, velocidad: 28, mordida: 160,
    ataque: 25, defensa: 50, fuerza: 58, agilidad: 55, ferocidad: 75, resistencia: 85, inteligencia: 100,
    armas: "Haka intimidante y placaje de rugby",
    fortaleza: "Los All Blacks son de los equipos más ganadores de la historia del deporte.",
    debilidad: "Primero hace la haka completa… y el rival ataca mientras tanto.",
    dato: "La haka es una danza tradicional maorí que se hace antes de cada partido.",
  },
];
