/*
 * Movimientos de cada luchador para la animación: [nombre del golpe, emoji del impacto].
 * Si un luchador no tiene golpes propios, se usan los de su categoría.
 */
const GOLPES = {
  leon: [["un zarpazo a la cara", "🐾"], ["una mordida al cuello", "🦷"], ["un rugido que hace temblar el suelo", "📢"]],
  elefante: [["un trompazo", "💥"], ["una embestida con los colmillos", "🗡️"], ["un pisotón de 6 toneladas", "🦶"]],
  rinoceronte: [["una embestida a 50 km/h", "💥"], ["un cornazo", "🗡️"], ["un resoplido furioso", "💨"]],
  hipopotamo: [["un mordisco de 1.800 PSI", "🦷"], ["una embestida", "💥"], ["un bostezo intimidante", "😮"]],
  grizzly: [["un zarpazo demoledor", "🐾"], ["un abrazo de oso (del malo)", "🫂"], ["una mordida", "🦷"]],
  guepardo: [["un ataque a 110 km/h", "💨"], ["una mordida rápida", "🦷"], ["un zarpazo relámpago", "⚡"]],
  hiena: [["una mordida tritura-huesos", "🦷"], ["una risa desquiciada", "😂"], ["un tirón de pierna", "🐾"]],
  bufalo: [["una embestida con el casco", "💥"], ["un cornazo", "🗡️"], ["un pisotón", "🦶"]],
  canguro: [["una doble patada apoyado en la cola", "🦶"], ["un gancho de boxeo canguro", "🥊"], ["un abrazo con patada", "💥"]],
  lobo: [["una mordida al tobillo", "🦷"], ["un aullido para pedir refuerzos (no vino nadie)", "🌕"], ["un ataque por el flanco", "🐾"]],
  komodo: [["una mordida venenosa", "🧪"], ["un coletazo", "💥"], ["un lengüetazo amenazante", "👅"]],
  tejon: [["un ataque sin miedo alguno", "😤"], ["un arañazo", "🐾"], ["una mordida kamikaze", "🦷"]],
  tigre: [["un zarpazo", "🐾"], ["una mordida a la nuca", "🦷"], ["un salto emboscada", "💥"]],
  gorila: [["un golpe de pecho y puñetazo", "👊"], ["un manotazo", "💥"], ["un lanzamiento de rama", "🪵"]],
  jaguar: [["una mordida al cráneo", "🦷"], ["un salto desde un árbol", "🌳"], ["un zarpazo", "🐾"]],
  chimpance: [["una mordida furiosa", "🦷"], ["un lanzamiento de… mejor no decirlo", "💩"], ["un jalón de brazos", "💪"]],
  anaconda: [["un abrazo constrictor", "🌀"], ["una mordida de agarre", "🦷"], ["un apretón mortal", "🌀"]],
  cocodrilo: [["el giro de la muerte", "🌀"], ["una mordida de 3.700 PSI", "🦷"], ["un coletazo", "💥"]],
  arpia: [["un ataque en picada", "🪶"], ["un garrazo", "🦅"], ["un aletazo", "💨"]],
  tiburon: [["una mordida desde abajo", "🦈"], ["un ataque sorpresa", "💥"], ["un embiste con el hocico", "🌊"]],
  orca: [["un embiste a toda velocidad", "🌊"], ["una mordida", "🦷"], ["un coletazo gigante", "💥"]],
  pulpo: [["un lanzamiento de tinta", "🖤"], ["un abrazo de 8 brazos", "🐙"], ["un picotazo venenoso", "🧪"]],
  morena: [["una mordida con doble mandíbula", "🦷"], ["un ataque desde la cueva", "🕳️"], ["un tirón", "💥"]],
  delfin: [["un cabezazo con el hocico", "💥"], ["un salto acrobático", "🌊"], ["una risita burlona", "😂"]],
  oso_polar: [["un zarpazo helado", "🐾"], ["una mordida", "🦷"], ["un aplastamiento de 450 kg", "💥"]],
  tigre_siberiano: [["un zarpazo", "🐾"], ["una mordida a la garganta", "🦷"], ["una emboscada en la nieve", "❄️"]],
  morsa: [["un colmillazo de 1 metro", "🗡️"], ["un panzazo", "💥"], ["un bigotazo", "🥸"]],
  gloton: [["un ataque demoníaco", "😈"], ["una mordida rompe-huesos", "🦷"], ["un arañazo", "🐾"]],
  leopardo_nieves: [["un salto de 15 metros", "💨"], ["una mordida", "🦷"], ["un coletazo esponjoso", "🧣"]],
  aguila_real: [["una picada a 240 km/h", "💨"], ["un garrazo", "🦅"], ["un picotazo", "💥"]],
  humano: [["un puñetazo torpe", "👊"], ["una patada a lo que salga", "🦶"], ["un grito de '¡ya para!'", "😱"]],
  mma: [["una patada giratoria", "🦶"], ["un derribo de doble pierna", "💥"], ["un mataleón", "🌀"]],
  strongman: [["un levantamiento de 500 kg", "🏋️"], ["un abrazo de oso humano", "🫂"], ["un lanzamiento de piedra de Atlas", "🪨"]],
  cazador: [["un lanzazo", "🗡️"], ["una estocada", "⚔️"], ["un golpe con el mango", "🪵"]],
  hormiga_bala: [["una picadura nivel 'disparo'", "🔫"], ["un mordisco minúsculo", "🐜"], ["un ataque con toda su alma", "💥"]],
  hormigas_legionarias: [["una marea de mordiscos", "🐜"], ["un rodeo total", "🌀"], ["un puente de hormigas", "🌉"]],
  tarantula: [["un lanzamiento de pelos urticantes", "✨"], ["una mordida con colmillos", "🦷"], ["un siseo (sí, sisean)", "💨"]],
  viuda_negra: [["una mordida neurotóxica", "🧪"], ["una trampa de telaraña", "🕸️"], ["un ataque sigiloso", "🖤"]],
  escorpion: [["un aguijonazo", "🧪"], ["un pellizco de pinzas", "🦂"], ["un contraataque", "💥"]],
  avispa_gigante: [["un aguijonazo de 6 mm", "🧪"], ["una decapitación con mandíbulas", "✂️"], ["un zumbido aterrador", "📢"]],
  enjambre_avispas: [["una nube de aguijones", "🧪"], ["una persecución sin fin", "🌪️"], ["un ataque coordinado", "🐝"]],
  abeja: [["su único aguijonazo", "🧪"], ["un zumbido valiente", "📢"], ["un vuelo kamikaze", "💥"]],
  abejas_africanizadas: [["mil picaduras al mismo tiempo", "🧪"], ["una persecución de 400 metros", "🌪️"], ["un enjambre a la cara", "🐝"]],
  pirañas: [["un frenesí de mordidas", "🦷"], ["un ataque en grupo", "🐟"], ["un mordisco relámpago", "⚡"]],
  boxeador: [["un jab-jab-cross", "🥊"], ["un gancho al hígado", "🥊"], ["un uppercut", "💥"]],
  muaythai: [["un codazo", "💥"], ["un rodillazo volador", "🦵"], ["una patada con tibia de acero", "🦶"]],
  crossfitero: [["100 burpees intimidantes", "🔥"], ["un kipping pull-up al aire", "💪"], ["un discurso sobre CrossFit", "🗣️"]],
  fisicoculturista: [["una pose de doble bíceps", "💪"], ["un golpe lento pero pesado", "👊"], ["un batido de proteína a la cara", "🥤"]],
  sumo: [["un empujón de 150 kg", "💥"], ["un lanzamiento de sal ceremonial", "🧂"], ["un pisotón shiko", "🦶"]],
  latino: [["un chanclazo teledirigido", "🩴"], ["un '¡te voy a dar una!'", "🗣️"], ["un paso de salsa evasivo", "💃"]],
  chino: [["una patada de película de Jackie Chan", "🦶"], ["un ataque con palillos", "🥢"], ["un movimiento de Tai Chi del abuelo", "☯️"]],
  japones: [["una reverencia seguida de llave de judo", "🙇"], ["un karatazo", "🥋"], ["un '¡sumimasen!' y golpe", "💥"]],
  coreano: [["una patada de taekwondo", "🦶"], ["una táctica del servicio militar", "🎖️"], ["un corazón con los dedos (distracción)", "🫰"]],
  kpoper: [["un golpe de lightstick", "💜"], ["un ataque del fandom en redes", "📱"], ["un fancam que hipnotiza", "📸"]],
};

const GOLPES_CATEGORIA = {
  sabana: [["un ataque feroz", "💥"], ["una mordida", "🦷"], ["un zarpazo", "🐾"]],
  selva: [["un ataque sorpresa", "💥"], ["una mordida", "🦷"], ["un zarpazo", "🐾"]],
  agua: [["una embestida", "🌊"], ["una mordida", "🦷"], ["un coletazo", "💥"]],
  nieve: [["un zarpazo", "🐾"], ["una mordida", "🦷"], ["un ataque helado", "❄️"]],
  aire: [["un ataque en picada", "💨"], ["un garrazo", "🦅"], ["un picotazo", "💥"]],
  bichos: [["una picadura", "🧪"], ["un mordisco", "🦷"], ["un ataque sorpresa", "💥"]],
  humano: [["un puñetazo", "👊"], ["una patada", "🦶"], ["un empujón", "💥"]],
};

/* Momentos absurdos que pasan en medio de la pelea (no cambian el resultado). */
const EVENTOS = {
  general: [
    "🩴 Alguien del público le lanza una chancla al árbitro.",
    "🍺 Un espectador pide otra ronda de cervezas. Nadie está mirando la pelea.",
    "🐧 Un pingüino perdido cruza la arena, confundido.",
    "📱 El árbitro se detiene a contestar un audio de WhatsApp.",
    "🎶 Empieza a sonar 'Despacito' y ambos dudan un segundo.",
    "🌮 Pasa el señor de los tacos. Pausa técnica de 3 segundos.",
    "📸 Un turista pide una selfie con los dos luchadores.",
    "🙏 La abuela de alguien en el público empieza a rezar.",
    "🦆 Un pato grazna. Nadie sabe de dónde salió.",
    "🧢 El comentarista pierde la gorra de la emoción.",
  ],
  sabana: ["🦒 Una jirafa mira desde lejos, juzgando.", "🌪️ Un remolino de polvo nubla la vista."],
  selva: ["🐒 Unos monos lanzan mangos desde los árboles.", "🦜 Un loro repite los insultos del público."],
  rio: ["🐸 Una rana salta sobre la cabeza del árbitro.", "🛶 Pasa un turista en canoa grabando todo."],
  oceano: ["🐠 Pasa Nemo buscando a su papá.", "🚢 Un crucero se detiene a mirar."],
  nieve: ["☃️ Alguien construyó un muñeco de nieve en la esquina.", "🌨️ Se desata una ventisca por un segundo."],
};
